spring:

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  redis:
    host: localhost
    port: 6379

reddit:
  client-id: ${REDDIT_CLIENT_ID}
  secret: ${REDDIT_SECRET}
  username: ${REDDIT_USERNAME}
  password: ${REDDIT_PASSWORD}

openai:
  api:
    key: ${OPENAI_API_KEY}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  port: ${ELASTICSEARCH_PORT}
