spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local # 기본값, EC2에서는 prod로 override

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    notify-keyspace-events: Ex