spring:

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

reddit:
  client-id: ${REDDIT_CLIENT_ID}
  secret: ${REDDIT_SECRET}
  username: ${REDDIT_USERNAME}
  password: ${REDDIT_PASSWORD}

openai:
  api:
    key: ${OPENAI_API_KEY}



management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: devscoop-api
