spring:
  profiles:
    active: local # 기본값, EC2에서는 prod로 override

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 100
        order_inserts: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
