spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local # 기본값, EC2에서는 prod로 override

  datasource:
    url: jdbc:h2:mem:testdb  # 또는 임시로 in-memory H2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 100
        order_inserts: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    notify-keyspace-events: Ex