spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

reddit:
  client-id: ${REDDIT_CLIENT_ID}
  secret: ${REDDIT_SECRET}
  username: ${REDDIT_USERNAME}
  password: ${REDDIT_PASSWORD}

openai:
  api:
    key: ${OPENAI_API_KEY}

elasticsearch:
  uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: devscoop-api
